version: '3.9'
services:
  auth_service:
    build: ./services/auth_service
    ports:
      - "8000:8000"
    volumes:
      - ./services/auth_service:/code
    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
