# Generated by Django 5.1.2 on 2025-08-27 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50, unique=True)),
                ('accountId', models.IntegerField()),
                ('firstName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('localeCode', models.CharField(blank=True, max_length=10, null=True)),
                ('balanceAmount', models.FloatField(blank=True, null=True)),
                ('apiKey', models.CharField(blank=True, max_length=100, null=True)),
                ('isDev', models.BooleanField(default=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isPartner', models.BooleanField(default=False)),
                ('TRC20Address', models.CharField(blank=True, max_length=100, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('discountRate', models.FloatField(blank=True, null=True)),
                ('bonusChargeRate', models.FloatField(blank=True, null=True)),
                ('referralBalance', models.FloatField(blank=True, null=True)),
                ('referralCode', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_addresses', to='dashboard.account')),
            ],
        ),
    ]
