# Generated by Django 5.1.2 on 2025-08-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_gsmservice_gsmsim'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmservice',
            name='_id',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='callCenters',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='countryCode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='image',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='messageOTPLimit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='privatePartners',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='rentPrice',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='saleOffValue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='supportCall',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='supportSMS',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gsmservice',
            name='text',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gsmservice',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
