# Generated by Django 5.1.2 on 2025-08-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_gsmservice__id_gsmservice_callcenters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gsmservice',
            name='data',
        ),
        migrations.AlterField(
            model_name='gsmservice',
            name='callCenters',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gsmservice',
            name='privatePartners',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gsmservice',
            name='rentPrice',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
